version: "3"
services:

  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb-test"
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: --smallfiles --logpath=/dev/null

  bet-engine:
    image: bet-engine
    ports:
      - 8088:8088
    links:
      - mongodb

